$sqlPath = "C:\Users\DELL\Downloads\database.sql"

$sql = @'

-- 1. SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_USER        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONFIG      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANOMALY_TYPE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STATUS_TYPE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IMPORT_BATCH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXCEL_TRX    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CORE_TRX     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECON_JOB    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RECON_RESULT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT_LOG    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- 2. TABLES
-- ============================================================

-- Table BAMIS_USER
CREATE TABLE BAMIS_USER (
    ID              NUMBER          NOT NULL,
    USERNAME        VARCHAR2(50)    NOT NULL,
    PASSWORD_HASH   VARCHAR2(100)   NOT NULL,
    FULL_NAME       VARCHAR2(100)   NOT NULL,
    ROLE            VARCHAR2(20)    NOT NULL,
    ACTIVE          NUMBER(1)       NOT NULL,
    MUST_CHANGE_PWD NUMBER(1)       NOT NULL,
    CREATED_BY      NUMBER,
    CREATED_AT      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UK_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_USER_ROLE CHECK (ROLE IN ('ADMIN','SUPERVISEUR','AGENT')),
    CONSTRAINT CK_USER_ACTIVE CHECK (ACTIVE IN (0,1)),
    CONSTRAINT CK_USER_PWD CHECK (MUST_CHANGE_PWD IN (0,1))
);

-- Table BAMIS_CONFIG
CREATE TABLE BAMIS_CONFIG (
    ID              NUMBER          NOT NULL,
    CONFIG_KEY      VARCHAR2(50)    NOT NULL,
    CONFIG_VALUE    VARCHAR2(200)   NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    CONSTRAINT PK_CONFIG PRIMARY KEY (ID),
    CONSTRAINT UK_CONFIG_KEY UNIQUE (CONFIG_KEY)
);

-- Table BAMIS_ANOMALY_TYPE
CREATE TABLE BAMIS_ANOMALY_TYPE (
    ID       NUMBER        NOT NULL,
    CODE     VARCHAR2(50)  NOT NULL,
    LABEL    VARCHAR2(200) NOT NULL,
    SEVERITY VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_ANOMALY_TYPE PRIMARY KEY (ID),
    CONSTRAINT UK_ANOMALY_CODE UNIQUE (CODE),
    CONSTRAINT CK_ANOMALY_SEVERITY CHECK (SEVERITY IN ('CRITIQUE','MAJEURE','MOYENNE','MINEURE'))
);

-- Table BAMIS_STATUS_TYPE
CREATE TABLE BAMIS_STATUS_TYPE (
    ID       NUMBER        NOT NULL,
    CODE     VARCHAR2(30)  NOT NULL,
    LABEL    VARCHAR2(100) NOT NULL,
    IS_VALID NUMBER(1)     NOT NULL,
    SEVERITY VARCHAR2(20),
    CONSTRAINT PK_STATUS_TYPE PRIMARY KEY (ID),
    CONSTRAINT UK_STATUS_CODE UNIQUE (CODE)
);

-- Table BAMIS_IMPORT_BATCH
CREATE TABLE BAMIS_IMPORT_BATCH (
    ID          NUMBER        NOT NULL,
    FILE_NAME   VARCHAR2(255) NOT NULL,
    CUT_OFF_ID  VARCHAR2(50)  NOT NULL,
    TOTAL_ROWS  NUMBER        NOT NULL,
    STATUS      VARCHAR2(20)  NOT NULL,
    IMPORTED_BY NUMBER        NOT NULL,
    IMPORTED_AT TIMESTAMP     NOT NULL,
    CONSTRAINT PK_IMPORT_BATCH PRIMARY KEY (ID),
    CONSTRAINT UK_BATCH_CUTOFF UNIQUE (CUT_OFF_ID),
    CONSTRAINT CK_BATCH_STATUS CHECK (STATUS IN ('IMPORTED','RECONCILED','ERROR')),
    CONSTRAINT FK_BATCH_USER FOREIGN KEY (IMPORTED_BY) REFERENCES BAMIS_USER(ID)
);

-- Table BAMIS_EXCEL_TRX
CREATE TABLE BAMIS_EXCEL_TRX (
    ID               NUMBER         NOT NULL,
    BATCH_ID         NUMBER         NOT NULL,
    CUT_OFF_ID       VARCHAR2(50)   NOT NULL,
    SWITCH_REF       VARCHAR2(100),
    TRANS_DATE       TIMESTAMP,
    ORIG_INST        VARCHAR2(50),
    ORIG_PHONE       VARCHAR2(50),
    RECEIV_INST_ID   VARCHAR2(50),
    RECEIV_PHONE     VARCHAR2(50),
    MONTANT          NUMBER(18,2),
    TX_TYPE          VARCHAR2(50),
    CONSTRAINT PK_EXCEL_TRX PRIMARY KEY (ID),
    CONSTRAINT FK_EXCEL_TRX_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BAMIS_IMPORT_BATCH(ID)
);

-- Table BAMIS_CORE_TRX
CREATE TABLE BAMIS_CORE_TRX (
    ID                  NUMBER         NOT NULL,
    TRX_CUT_OFF_ID      VARCHAR2(50),
    TRX_REQU_REFE_NUMB  VARCHAR2(100)  NOT NULL,
    TRX_TRAN_DATE_TIME  TIMESTAMP,
    TRX_PHONE           VARCHAR2(50),
    TRX_PHONE_DES       VARCHAR2(50),
    TRX_TRAN_AMOU       NUMBER(18,2),
    TRX_TRANS_TYPE      VARCHAR2(50),
    TRX_INS_IDEN        VARCHAR2(50),
    TRX_INS_IDEN_DES    VARCHAR2(50),
    TRX_STATUS          VARCHAR2(30),
    TRX_SETTLED         NUMBER(1),
    TRX_TRANS_DIRE      VARCHAR2(20),
    CONSTRAINT PK_CORE_TRX PRIMARY KEY (ID)
);

-- Table BAMIS_RECON_JOB
CREATE TABLE BAMIS_RECON_JOB (
    ID                  NUMBER    NOT NULL,
    BATCH_ID            NUMBER    NOT NULL,
    LAUNCHED_BY         NUMBER    NOT NULL,
    LAUNCHED_AT         TIMESTAMP NOT NULL,
    TOTAL_EXCEL         NUMBER,
    TOTAL_CORE          NUMBER,
    TOTAL_CONFORME      NUMBER,
    TOTAL_NON_CONFORME  NUMBER,
    TOTAL_MISSING_CORE  NUMBER,
    TOTAL_MISSING_EXCEL NUMBER,
    CONSTRAINT PK_RECON_JOB PRIMARY KEY (ID),
    CONSTRAINT FK_JOB_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BAMIS_IMPORT_BATCH(ID),
    CONSTRAINT FK_JOB_USER FOREIGN KEY (LAUNCHED_BY) REFERENCES BAMIS_USER(ID)
);

-- Table BAMIS_RECON_RESULT
CREATE TABLE BAMIS_RECON_RESULT (
    ID              NUMBER         NOT NULL,
    JOB_ID          NUMBER         NOT NULL,
    SWITCH_REF      VARCHAR2(100),
    MONTANT_EXCEL   NUMBER(18,2),
    MONTANT_CORE    NUMBER(18,2),
    ECART           NUMBER(18,2),
    STATUT_TRX      VARCHAR2(30),
    SETTLED         NUMBER(1),
    PRESENCE        VARCHAR2(20),
    CONFORMITE      VARCHAR2(20),
    ANOMALY_CODE    VARCHAR2(50),
    SEVERITY        VARCHAR2(20),
    DETAILS         VARCHAR2(500),
    CONSTRAINT PK_RECON_RESULT PRIMARY KEY (ID),
    CONSTRAINT FK_RESULT_JOB FOREIGN KEY (JOB_ID) REFERENCES BAMIS_RECON_JOB(ID)
);

-- Table BAMIS_AUDIT_LOG
CREATE TABLE BAMIS_AUDIT_LOG (
    ID          NUMBER         NOT NULL,
    USER_ID     NUMBER         NOT NULL,
    ACTION      VARCHAR2(100)  NOT NULL,
    DETAILS     VARCHAR2(1000),
    CREATED_AT  TIMESTAMP      NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES BAMIS_USER(ID)
);

-- ============================================================
-- 3. INDEX
-- ============================================================
CREATE INDEX IDX_EXCEL_TRX_BATCH    ON BAMIS_EXCEL_TRX(BATCH_ID);
CREATE INDEX IDX_EXCEL_TRX_CUTOFF   ON BAMIS_EXCEL_TRX(CUT_OFF_ID);
CREATE INDEX IDX_CORE_TRX_CUTOFF    ON BAMIS_CORE_TRX(TRX_CUT_OFF_ID);
CREATE INDEX IDX_CORE_TRX_REF       ON BAMIS_CORE_TRX(TRX_REQU_REFE_NUMB);
CREATE INDEX IDX_RECON_RESULT_JOB   ON BAMIS_RECON_RESULT(JOB_ID);
CREATE INDEX IDX_AUDIT_LOG_USER     ON BAMIS_AUDIT_LOG(USER_ID);

-- ============================================================
-- 4. DONNEES INITIALES
-- ============================================================

-- Types d'anomalies
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'MISSING_CORE','Manquante en base','CRITIQUE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'MISSING_EXCEL','Manquante dans Excel','CRITIQUE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'REVERSED','Transaction contre-passee','CRITIQUE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'CANCELLED','Transaction annulee','CRITIQUE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'REJECTED','Transaction rejetee','MAJEURE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'FAILED','Transaction en echec','MAJEURE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'INSTANCE','Transaction en instance','MAJEURE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'NOT_SETTLED','Transaction non reglee','MAJEURE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'PENDING','Transaction en attente','MOYENNE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'PROCESSING','Transaction en cours','MOYENNE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'INST_MISMATCH','Ecart institution','MOYENNE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'PHONE_MISMATCH','Ecart de numero','MOYENNE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'TYPE_MISMATCH','Ecart de type','MOYENNE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'AMOUNT_MISMATCH','Ecart de montant','MINEURE');
INSERT INTO BAMIS_ANOMALY_TYPE VALUES (SEQ_ANOMALY_TYPE.NEXTVAL,'DATE_MISMATCH','Ecart de date','MINEURE');

-- Types de statuts
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'APPROVED','Validee',1,NULL);
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'EXECUTED','Executee',1,NULL);
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'INSTANCE','En instance',0,'MAJEURE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'PENDING','En attente',0,'MOYENNE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'PROCESSING','En cours',0,'MOYENNE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'REJECTED','Rejetee',0,'MAJEURE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'FAILED','Echec',0,'MAJEURE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'CANCELLED','Annulee',0,'CRITIQUE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'REVERSED','Contre-passee',0,'CRITIQUE');
INSERT INTO BAMIS_STATUS_TYPE VALUES (SEQ_STATUS_TYPE.NEXTVAL,'TIMEOUT','Expiree',0,'MAJEURE');

-- Configuration systeme
INSERT INTO BAMIS_CONFIG VALUES (SEQ_CONFIG.NEXTVAL,'AMOUNT_TOLERANCE','0','Tolerance autorisee sur l ecart de montant');
INSERT INTO BAMIS_CONFIG VALUES (SEQ_CONFIG.NEXTVAL,'DATE_TOLERANCE_SECONDS','0','Tolerance autorisee sur l ecart de date en secondes');
INSERT INTO BAMIS_CONFIG VALUES (SEQ_CONFIG.NEXTVAL,'MAX_IMPORT_ROWS','100000','Nombre maximum de lignes par import');

-- Utilisateur admin par defaut
-- Mot de passe : Admin@2026 (BCrypt)
INSERT INTO BAMIS_USER VALUES (
    SEQ_USER.NEXTVAL,
    'admin',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
    'Administrateur Systeme',
    'ADMIN',
    1,
    0,
    NULL,
    SYSTIMESTAMP
);

COMMIT;

